const Nationality = {
  AU: "Australian",
  BR: "Brazilian",
  CA: "Canadian",
  CH: "Switzerlandian",
  DE: "German",
  DK: "Denmarkian",
  ES: "Spainian",
  FI: "Finlandian",
  FR: "Franch",
  GB: "British",
  IE: "Irish",
  IN: "Indian",
  IR: "Iranian",
  MX: "Mexican",
  NL: "Netherlandian",
  NO: "Norwadian",
  NZ: "New Zealand",
  RS: "Palestinian Territory",
  TR: "Turkish",
  UA: "Ukrainian",
  US: "American",
};

export { Nationality };
